AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'spec/support/**/*'
    - 'config/**/*'
    - 'Rakefile'
    - 'app/controllers/graphql_controller.rb'
Naming/MemoizedInstanceVariableName:
  Enabled: false
Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/ClassAndModuleChildren:
  Enabled: false
